### ISSUE TITLE
Clarification: Page 10

### ISSUE THREAD

**Issue by nbates** [EEHPCWG/PowerMeasurementMethodology#57]
Page 10: "For Level 2, all subsystems participating in the workload must be measured and, if not measured, their contribution must be estimated." I would suggest to add "The contribution of the compute node subsystem must be measured."

**Comment by nbates** [comment]
This seems redundant and not necessary.

**Comment by davidrohr** [comment]
To me it seems not redundant. I interprete the initial sentense such, that you could estimate the compute node subsystem if you do not measure it.
