### ISSUE TITLE
Page 13: L1 Entire Core Phase clarification

### ISSUE THREAD

**Issue by nbates** [EEHPCWG/PowerMeasurementMethodology#59]
Page 13 second last paragraph: We should add here that for l1 the averaged measurement must cover the entire core phase.

**Comment by nbates** [comment]
If L1, then it doesn't seem necessary.  If L2, then yes.

**Comment by davidrohr** [comment]
I do not remember, L1 correctly states that you have to measure the whole core phase in the paragraph above. So I think we can close this.
