### ISSUE TITLE
Redundancy and Confusion

### ISSUE THREAD

**Issue by nbates** [EEHPCWG/PowerMeasurementMethodology#79]
4) I feel that there is a alot of redundancy in the document - that also leads to some contradictions. I feel that particular aspect, e.g. "Level one measurement at least once per second" should appear not more than three times, e.g., in a summary text, a detailed text and a summary table. Right now it is mentioned in 1. (introduction Level 1), 2.2.1 (Terminology), 2.2.2, Table 2.1, 2.4.3 (Level 1) and 5 (Definitions). I think the difficulty is that document has orthogonal structures of at least aspects and levels.

Thomas Ilsche email 10 July 2015

**Comment by tilsche** [comment]
Superseded by #101
