### ISSUE TITLE
15 is too many for L1

### ISSUE THREAD

**Issue by nbates** [EEHPCWG/PowerMeasurementMethodology#82]
"For Level 1, both the compute-node subsystem and the interconnect must be re-
ported. The compute-node subsystem power must be measured. For the compute
subsystem measure a minimum of 2kw of power, 10% of the system, or 15 nodes
whichever is largest, or the whole machine if smaller than the
largest requirement."

In general, this is quite fair and reasonable definition, except the
node number of 15.
2kw of power and 10% of the system will be no problem for any one, for sure.
But node number of 15 will be a potential problem. It requires either
15 of 1ch Power Meter or 5 of 3ch Power Meter.

In our case, we are using Japanese Hioki Power Meter.
http://www.spec.org/power/docs/SPECpower-Device_List.html#mozTocId266535
But unfortunately, there is only 1ch Power Meter accepted by
SPECpower device list.
There are 3ch model from Hioki, which we are using daily together with 1ch model.
If the new rule will be in effective, we have to buy 14 more 1ch Power Meter.
Or, comparable multi-channel model of the Power Meter should be allowed to use.

Even in the case where 3 or 4 ch Power Meter will be allowed to use,
still smaller system around 200TFLOPS performance will have to be
measured with around 30-45% of entire nodes (4-6 TFLOPS/node is
possible with GPGPUs or accelerators in these days).

For our case, it will be no problem to measure 15 nodes, if necessary.
But for the site or team with even smaller size of operation who
wants to submit to Green500, it will be a bit high hurdle to measure
30-45% of the entire nodes.
If Green500 wants to keep the door as open as possible for submission
even with fair enough new policy, I think minimum node number should
be a bit less like 8 or 9. (10 requires 4 of 3ch Power Meter.)

And I request comparable or better multi-channel Power Meter will be
allowed to use for the measurement.
e.g.
Hioki POPWER HiTESTER 3334 (1ch, +- 0.2% basic accuracy, SPECpower accepted)
https://www.hioki.com/products/recorder_logger_current/recorders/402

Hioki POWER METER PW3337 (3ch, +- 0.1% basic accuracy, SPECpower not accepted)
https://www.hioki.com/products/power_current_sensor/power_meters/1396

Motoaki Saito, M.D., Ph.D.

**Comment by davidrohr** [comment]
There is no need to use 15 power meters to measure 15 nodes.
One can connect multiple power meters to the same node.
A three-phase meter should be capable of measuring 15 nodes of 1 kW each.

Still, I see a valid point here for even more powerfull nodes.
If each node would e.g. drain 6 kW, 15 nodes would require 90 kW, which is a lot.
And besides, 10% of a 1MW system would be 100 kW, also much for level 1.

My suggestion is that we add one exception:
"As soon as you are measuring 30 kW or above, you do not have to meet the other three requirements"
